#!/usr/bin/env python
"""Re-observe existing datasets at a new ``obs_noise_std``.

The state trajectories in ``data.h5`` do not depend on the observation noise
level: ``generate.py`` generates one set of trajectories and then applies the
observation operator with whichever noise level is configured. So adding a
new obs-noise variation (e.g. sigma = 0.2) for an existing dataset family
does NOT require re-integrating the dynamics — we can just reload the
stored trajectories and re-apply the observation step.

This script automates that for a directory tree of datasets, e.g.::

    python reobserve_obs_noise.py \\
        --src-root /projects/.../datasets/l96_dims \\
        --target-noise 0.2 \\
        --seed 42

For each source directory it writes a new directory at ``--dst-root``
(default: same as ``--src-root``) whose name is generated by the project's
own ``generate_dataset_directory_name`` so the new variants slot in next to
the existing ones.

Source dirs that share the same trajectories (different obs-noise variants
of the same (d, H, pnoise) cell) collapse to a single re-observe call;
the lex-smallest source is used as the canonical trajectory provider so
the choice is deterministic.
"""

from __future__ import annotations

import argparse
import hashlib
import logging
import os
import sys
from pathlib import Path
from typing import Dict, Optional, Tuple, Type

import h5py
import numpy as np
import torch

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from data import (  # noqa: E402
    DataAssimilationConfig,
    DynamicalSystem,
    KuramotoSivashinsky,
    Lorenz63,
    Lorenz96,
    generate_dataset_directory_name,
    load_config_yaml,
    observations_from_trajectories,
    save_config_yaml,
    save_generated_data,
)


def detect_system(config: DataAssimilationConfig) -> Tuple[Type[DynamicalSystem], str]:
    """Pick the DynamicalSystem subclass implied by ``config.system_params``."""
    sp = config.system_params or {}
    if "dim" in sp and "F" in sp:
        return Lorenz96, "lorenz96"
    if "sigma" in sp and "rho" in sp and "beta" in sp:
        return Lorenz63, "lorenz63"
    if "J" in sp and "L" in sp:
        return KuramotoSivashinsky, "ks"
    raise ValueError(
        f"Could not infer dynamical system from system_params keys: {list(sp.keys())}"
    )


def deterministic_seed(base_seed: int, dst_name: str) -> int:
    """Stable per-dataset seed so reruns reproduce bit-for-bit."""
    h = hashlib.sha256(f"{base_seed}:{dst_name}".encode()).digest()
    return int.from_bytes(h[:4], "little")


def reobserve_one(
    src_dir: Path,
    dst_root: Path,
    target_noise: float,
    base_seed: Optional[int],
    force: bool,
    dry_run: bool,
) -> Optional[Tuple[Path, Path]]:
    """Re-observe a single source dataset.

    Returns (src_dir, dst_dir) if a new directory was (or would be) written,
    None if the source was skipped.
    """
    config_path = src_dir / "config.yaml"
    h5_path = src_dir / "data.h5"
    if not config_path.exists() or not h5_path.exists():
        logging.warning("Skip (missing config.yaml or data.h5): %s", src_dir)
        return None

    cfg = load_config_yaml(config_path)
    cfg.obs_noise_std = float(target_noise)

    system_cls, system_name = detect_system(cfg)
    dst_name = generate_dataset_directory_name(cfg, system_name=system_name)
    dst_dir = dst_root / dst_name

    if dst_dir.exists() and (dst_dir / "data.h5").exists() and not force:
        logging.info("Exists, skipping: %s", dst_dir)
        return None

    if dry_run:
        print(f"DRY-RUN  {src_dir.name}\n   ->    {dst_name}")
        return src_dir, dst_dir

    if base_seed is not None:
        seed = deterministic_seed(base_seed, dst_name)
        np.random.seed(seed)
        torch.manual_seed(seed)

    system = system_cls(cfg)

    with h5py.File(h5_path, "r") as f:
        obs_mask = f["obs_mask"][...]
        train_traj = f["train"]["trajectories"][...]
        val_traj = f["val"]["trajectories"][...]
        test_traj = f["test"]["trajectories"][...]

    obs_train, _ = observations_from_trajectories(
        system, train_traj, cfg.obs_frequency, cfg.len_trajectory
    )
    obs_val, _ = observations_from_trajectories(
        system, val_traj, cfg.obs_frequency, cfg.len_trajectory
    )
    obs_test, _ = observations_from_trajectories(
        system, test_traj, cfg.obs_frequency, cfg.len_trajectory
    )

    splits_unscaled: Dict = {
        "train": {"trajectories": train_traj, "observations": obs_train},
        "val": {"trajectories": val_traj, "observations": obs_val},
        "test": {"trajectories": test_traj, "observations": obs_test},
    }

    dst_dir.mkdir(parents=True, exist_ok=True)
    save_generated_data(dst_dir, splits_unscaled, obs_mask)
    save_config_yaml(cfg, dst_dir / "config.yaml")
    logging.info("Wrote: %s", dst_dir)
    return src_dir, dst_dir


def dedupe_sources(
    src_dirs, dst_root: Path, target_noise: float
) -> Dict[str, Path]:
    """Map each unique destination dataset name to a single source dir.

    Multiple source dirs that differ only in ``obs_noise_std`` collapse to
    the same destination; we pick the lex-smallest source so the choice is
    deterministic and corresponds to the smallest-sigma original (whose
    trajectories are the canonical reference for the dataset family).
    """
    by_dst: Dict[str, Path] = {}
    for src in sorted(src_dirs):
        config_path = src / "config.yaml"
        if not config_path.exists():
            continue
        try:
            cfg = load_config_yaml(config_path)
        except Exception as exc:  # noqa: BLE001
            logging.warning("Skip %s: failed to parse config (%s)", src, exc)
            continue
        cfg.obs_noise_std = float(target_noise)
        try:
            _, system_name = detect_system(cfg)
        except ValueError as exc:
            logging.warning("Skip %s: %s", src, exc)
            continue
        dst_name = generate_dataset_directory_name(cfg, system_name=system_name)
        by_dst.setdefault(dst_name, src)
    return by_dst


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--src-root", type=str, required=True,
                   help="Root containing source dataset directories.")
    p.add_argument("--dst-root", type=str, default=None,
                   help="Root for new dataset directories (default: same as --src-root).")
    p.add_argument("--target-noise", type=float, default=0.2,
                   help="New obs_noise_std value to generate (default: 0.2).")
    p.add_argument("--pattern", type=str, default="*",
                   help="Glob pattern for source dirs under --src-root (default: '*').")
    p.add_argument("--seed", type=int, default=42,
                   help="Base RNG seed; combined with destination dir name for "
                        "per-dataset reproducibility (default: 42, matches gen_96_new.sh).")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing destination directories.")
    p.add_argument("--dry-run", action="store_true",
                   help="List planned source -> destination mappings without writing.")
    p.add_argument("--log-level", type=str, default="INFO")
    args = p.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s - %(levelname)s - %(message)s",
    )

    src_root = Path(args.src_root).resolve()
    dst_root = Path(args.dst_root).resolve() if args.dst_root else src_root
    if not src_root.is_dir():
        raise FileNotFoundError(src_root)
    dst_root.mkdir(parents=True, exist_ok=True)

    src_dirs = [d for d in src_root.glob(args.pattern) if d.is_dir()]
    print(f"Found {len(src_dirs)} candidate source dirs under {src_root} "
          f"(pattern={args.pattern!r}).")

    by_dst = dedupe_sources(src_dirs, dst_root, args.target_noise)
    print(f"Unique destination datasets after dedupe: {len(by_dst)}")

    written = 0
    skipped = 0
    for dst_name, src in sorted(by_dst.items()):
        result = reobserve_one(
            src,
            dst_root,
            target_noise=args.target_noise,
            base_seed=args.seed,
            force=args.force,
            dry_run=args.dry_run,
        )
        if result is None:
            skipped += 1
        else:
            written += 1

    print(
        f"Done. processed={written}, skipped={skipped}, "
        f"target_noise={args.target_noise}, dst_root={dst_root}"
    )


if __name__ == "__main__":
    main()
